# Site
repository: eigenbom
favicon: images/favicon.ico

# Personal info
name: Benjamin Porter
title: Game Developer
email: benjamin.porter@gmail.com
website: bp.io

# Social links
twitter_username: eigenbom
github_username:  eigenbom

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a games programmer with a background in computer science, mathematics, and art. I enjoy working on large projects and experimenting with new languages and technology. My primary interest is in procedural generation and the future of computational creativity in games.

  I'm very experienced with <mark>C++</mark>, <mark>Game Engines</mark> and <mark>Games Development</mark>. I also enjoy <mark>Procedural Generation</mark>.

  I’m familiar with Python and have had experience with most other languages, including Java, Typescript, C#, Haskell, Lua, and Lisp. I’ve had experience with developing game engines and using existing engines like Unity and Unreal.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  In addition to games development I have many other interests. For example:
   - Reading science fiction and fantasy
   - Pixel art
   - Playing guitar
   - Playing Board games and D&D
   - Spending time with my family

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
